version: "3"
services:
  lab:
    image: jupyter_clade1mpox:v03 
    container_name: clade1mpox_dev_container 
    build:
        context: .
        dockerfile: ./.devcontainer/Dockerfile

    ports:
      - "8800:8888" # http://localhost:8800/lab to launch Jupyter Lab
       
    volumes:
      - .:/home/jovyan/work

    command: >
        bash -c 'julia -e "using Pkg;Pkg.activate(\"./work\");Pkg.instantiate();Pkg.precompile()"
        && julia -e "using IJulia;IJulia.installkernel(\"Julia Multithreads\",env=Dict(\"JULIA_NUM_THREADS\" => \"14\",))" &&
        start.sh jupyter lab'
